
user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        location / {
            default_type application/json;
            return 200 '{"status":"running"} \n';
        }
        location /health {
            return 200 "healthy\n";
        }
    }
}
